### ISSUE TITLE
Print detailed stack on module load error

### ISSUE THREAD

**Issue by timeking** [requirejs/requirejs#1489]
Now in browser I see only error message with stack from requirejs. To fix problems in module it is better to print source stack, which is cause of error.

To achive this you need to fix one line:https://github.com/jrburke/requirejs/blob/master/require.js#L899
`console.error(err);`
replace with 
`console.error(err.stack);`

Thank you!

**Comment by jrburke** [comment]
Issue #1477 tracks reverting the change that lead to this unfortunate console.error in the first place, so this fixed by that revert, will be part of 2.2.0.

**Comment by dgoldstein0** [comment]
curious, what sort of module load error is this bug about?  I'm debating whether I should try out requirejs 2.1.23 since bug #1440 seems to be striking us a lot on 2.1.20, but this bug seems to be the only reason #1440 isn't actually fixed.
